version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dupword
    - embeddedstructfieldcheck  # Embedded struct formatting is stylistic
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder                 # Function ordering is developer's choice
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godoclint                 # Doc comment style (v2.8+ only)
    - godot
    - gosmopolitan              # I18n linter - not needed for this project
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - modernize                 # Modernization suggestions (v2.8+ only) - not always appropriate
    - nilerr
    - noinlineerr               # Inline error handling is idiomatic Go
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unparam
    - usetesting
    - varnamelen
    - wrapcheck
    - wsl                       # Whitespace linter (deprecated version)
    - wsl_v5                    # Whitespace linter (new version) - very opinionated
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use standard library errors package or fmt.Errorf with %w
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 150            # Start high, will reduce in Phase 5
    goconst:
      min-len: 3                # Minimum length of string constant
      min-occurrences: 5        # Start high to reduce noise, will lower in Phase 4
      match-constant: true      # Match constants
      numbers: false            # Don't check numbers (too noisy)
    godox:
      keywords:                 # Track these keywords
        - TODO
        - FIXME
        - BUG
        - XXX
        - HACK
        - OPTIMIZE
    revive:
      severity: warning
      enable-all-rules: false   # Start with selected rules
      rules:
        # High-value rules that catch real issues
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          arguments:
            - "checkPrivateReceivers"
            - "disableStutteringCheck"
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
          disabled: true          # Too opinionated for now
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
          disabled: true          # Too many false positives with interface implementations
        - name: unreachable-code
        - name: redefines-builtin-id
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 30        # Cyclomatic complexity
    funlen:
      lines: 120                # Maximum function length in lines (reduced from 150 in Phase 5)
      statements: 60            # Maximum function length in statements (reduced from 80 in Phase 5)
      ignore-comments: true     # Don't count comment lines
    gocognit:
      min-complexity: 30        # Cognitive complexity threshold (reduced from 40 in Phase 5)
    nestif:
      min-complexity: 5         # Maximum nesting depth (reduced from 7 in Phase 5)
    gosec:
      excludes:
        - G104  # Duplicated errcheck
        - G307  # Duplicated errcheck on file defer Close()
        - G115  # Integer overflow conversion - SLURM resource counts unlikely to overflow int32
        - G404  # Use of weak random generator - acceptable for test data and non-cryptographic randomness
        - G601  # Implicit memory aliasing - fixed in Go 1.22+ with new loop variable scoping
        - G602  # Slice index out of range - covered by bounds checking
    misspell:
      locale: US
      ignore-rules:
        - cancelled
        - cancelling
        - marshalled
        - marshalling
        - analyses
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
        - -SA9003   # Empty branch - placeholder branches reserved for future implementation
        - -ST1003   # Package naming - some packages use underscores for clarity
        - -QF1001   # De Morgan's law - readability preference
        - -QF1003   # Tagged switch - style preference
        - -QF1008   # Embedded field selector - intentional for clarity
    unparam:
      check-exported: false
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Test files - relax various linters
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - errchkjson
          - goconst
          - gocyclo
          - gosec
          - revive
          - staticcheck
        path: _test\.go
      # Test helpers
      - linters:
          - deadcode
          - unused
        path: test_helpers\.go
      # Phase 4 Complexity Linters - Pragmatic exclusions for inherent patterns
      # Constructor functions - inherently long due to metric initialization
      - linters:
          - funlen
          - gocognit
        text: 'Function .New\w+. (is too long|has cognitive complexity)'
      # Metrics initialization functions - repetitive Prometheus desc creation
      - linters:
          - funlen
        text: 'Function .new\w*[Mm]etrics. is too long'
      # Prometheus Describe methods - inherently long, listing all metrics
      - linters:
          - funlen
        text: 'Function .Describe. (is too long|has too many statements)'
      # Prometheus Collect methods - inherently long, collecting many metrics
      - linters:
          - funlen
        path: ^internal/collector/
        text: 'Function .Collect. (is too long|has too many statements)'
      # Configuration default initialization - repetitive field assignments
      - linters:
          - funlen
        path: internal/config/config\.go
        text: 'Function .Default.'
      # Complex collection methods requiring refactoring - tracked for Phase 5
      - linters:
          - funlen
          - gocognit
        path: internal/collector/job\.go
        text: '(Function .collectActiveJobs|cognitive complexity.*collectActiveJobs)'
      - linters:
          - funlen
        path: internal/collector/cluster_health_streaming\.go
        text: 'Function .collectStreamingMetrics'
      # Phase 5: Remaining complexity after tightening thresholds
      # These are candidates for future refactoring but acceptable for now
      - linters:
          - funlen
        path: internal/collector/
        text: 'Function .(collectStreamingMetrics|resetAllMetrics|collectAllMetrics|collectPartitionInfo|collectAccountStats|collectSecurityEvents|ReconfigureCollectors)'
      - linters:
          - funlen
        path: internal/server/
        text: 'Function .(handleGetProfile|handleDebugPerformance)'
      - linters:
          - funlen
        path: internal/metrics/docgen\.go
        text: 'Function .GenerateHelmChart'
      # accounts_simple and associations_simple refactored in Phase 5
      - linters:
          - funlen
          - gocognit
        path: internal/config/
        text: '(has too many statements|cognitive complexity.*(applySLURMEnvOverrides|validateSecurity))'
      - linters:
          - nestif
        path: internal/
        text: 'has complex nested blocks'
      # Test functions - can be legitimately long with multiple test cases
      - linters:
          - funlen
          - gocognit
        path: _test\.go
      # Main function - inherently long due to setup/configuration
      - linters:
          - funlen
        path: cmd/.*/main\.go
        text: 'Function .main.'
      # Collector package - common duplication patterns
      - linters:
          - dupl
        path: ^internal/collector/
      # Mock and test utilities
      - linters:
          - dupl
        path: ^internal/testutil/
      # Generated code markers
      - linters:
          - lll
        source: '^//go:generate '
      # Example code
      - linters:
          - dupl
          - errcheck
          - gosec
          - ineffassign
          - staticcheck
          - unused
        path: ^examples/
      # Command line tools
      - linters:
          - dupl
          - errcheck
          - staticcheck
          - unused
        path: ^cmd/
      # Benchmark code
      - linters:
          - bodyclose
          - errcheck
          - staticcheck
        path: ^test/benchmark/
      # Integration tests
      - linters:
          - bodyclose
          - errcheck
          - staticcheck
        path: ^test/integration/
      # Adapters with deprecated SLURM API usage
      - linters:
          - staticcheck
        path: internal/slurm/
        text: deprecated
      # Context nil checks in tests
      - linters:
          - staticcheck
        path: _test\.go
        text: do not pass a nil Context
      # Prometheus naming - intentional use of non-base time units for better UX
      # Users prefer _hours, _days, _minutes over converting to _seconds
      - linters:
          - promlinter
        path: ^internal/collector/
        text: 'use base unit "seconds" instead of'
      # Prometheus naming - intentional use of abbreviated units
      # GB/MB are more readable than bytes for storage/memory metrics
      - linters:
          - promlinter
        path: ^internal/collector/
        text: 'metric names should not contain abbreviated units'
      # Prometheus naming - _count suffix used intentionally for gauge metrics
      # These represent current counts, not histogram/summary observations
      - linters:
          - promlinter
        path: ^internal/collector/
        text: 'non-histogram and non-summary metrics should not have "_count" suffix'
      # Prometheus naming - _total suffix used intentionally for gauge metrics
      # These represent total capacity/allocation, not monotonic counters
      - linters:
          - promlinter
        path: ^internal/collector/
        text: 'non-counter metrics should not have "_total" suffix'
      # Prometheus naming - metric names include type for clarity
      - linters:
          - promlinter
        path: ^internal/collector/
        text: 'metric name should not include type'
      # Performance and cardinality metrics - intentional naming
      - linters:
          - promlinter
        path: ^internal/(performance|metrics)/
        text: 'non-counter metrics should not have "_total" suffix'
      # Spancheck - TraceAPICall returns cleanup function that calls span.End()
      - linters:
          - spancheck
        path: internal/tracing/tracer\.go
        text: 'return can be reached without calling span.End'
      # Phase 3 Linters - Pragmatic exclusions for intentional patterns
      # godox - Intentional TODO comments documenting preserved code and missing fields
      - linters:
          - godox
        path: ^internal/collector/
      - linters:
          - godox
        path: ^internal/(config|metrics|performance|server|slurm)/
        text: '(Unused field|Unused fields|unused|preserved for future)'
      # goconst - Intentional status/state string comparisons
      - linters:
          - goconst
        text: 'has \d+ occurrences, but such constant .* already exists'
      # revive - Empty blocks for channel draining (intentional pattern)
      - linters:
          - revive
        text: 'this block is empty, you can remove it'
      # revive - Context keys in test code
      - linters:
          - revive
        path: _test\.go
        text: 'context-keys-type'
      # revive - Var declarations in test code (mock nil clients)
      - linters:
          - revive
        path: _test\.go
        text: 'var-declaration.*Mock client'
      # revive - Indent-error-flow in existing code (will be refactored in Phase 4)
      - linters:
          - revive
        text: 'indent-error-flow'
      # revive - Context-as-argument in Prometheus collectors (chan first is idiomatic pattern)
      - linters:
          - revive
        path: ^internal/collector/
        text: 'context-as-argument'
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  # Formatters should only run with --fix, not during regular linting
  # enable:
  #   - gci
  #   - gofmt
  #   - gofumpt
  #   - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$
