# Production Environment Configuration
# This file contains production-specific settings for SLURM Exporter

# Environment metadata
environment:
  name: production
  cluster: main-cluster
  region: us-west-2
  compliance_level: high
  security_tier: restricted

# SLURM cluster configuration
slurm:
  clusters:
    main:
      rest_url: "https://slurm-head.prod.example.com:6820"
      auth_type: jwt
      timeout: 30s
      retry_count: 3
      retry_delay: 5s
      max_concurrent_requests: 10
      rate_limit: 100  # requests per minute
      
      # Connection pooling for production
      connection_pool:
        min_connections: 2
        max_connections: 10
        max_idle_time: 300s
        connection_ttl: 1800s
    
    backup:
      rest_url: "https://slurm-backup.prod.example.com:6820"
      auth_type: jwt
      timeout: 45s
      retry_count: 2
      enabled: false  # Enable for failover scenarios

# Server configuration optimized for production
server:
  address: ":8080"
  metrics_path: "/metrics"
  health_path: "/health"
  ready_path: "/ready"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  max_request_size: 10485760  # 10MB
  enable_pprof: false  # Disabled in production for security
  enable_cors: false
  cors_origins: []
  
  # Production TLS configuration
  tls:
    enabled: true
    cert_file: "/etc/tls/tls.crt"
    key_file: "/etc/tls/tls.key"
    min_version: "1.2"
    cipher_suites:
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  enable_caller: false
  enable_stacktrace: false
  
  # Structured logging fields
  fields:
    service: "slurm-exporter"
    environment: "production"
    cluster: "main-cluster"
    version: "${VERSION}"

# Collectors configuration optimized for production workloads
collectors:
  jobs:
    enabled: true
    collection_interval: 30s
    timeout: 15s
    max_age: 300s
    
    # Production metric filtering
    filters:
      metric_filter:
        enable_all: false
        include_metrics:
          - "slurm_job_state"
          - "slurm_job_cpus_allocated"
          - "slurm_job_memory_allocated"
          - "slurm_job_priority"
          - "slurm_job_queue_time_seconds"
          - "slurm_job_run_time_seconds"
          - "slurm_job_wait_time_seconds"
        exclude_metrics:
          - "slurm_job_feature_*"  # High cardinality
        skip_histograms: false
        skip_timing_metrics: false
    
    # Cardinality management for large clusters
    cardinality:
      max_labels: 5000
      sample_rate: 1.0
      max_series_per_label: 100
      cleanup_interval: 600s
    
    # Production labels
    custom_labels:
      cluster_name: "main-cluster"
      environment: "production"
      region: "us-west-2"
      compliance: "high"

  nodes:
    enabled: true
    collection_interval: 60s
    timeout: 30s
    max_age: 600s
    
    filters:
      metric_filter:
        enable_all: true
        exclude_metrics:
          - "slurm_node_feature_*"  # High cardinality features
          - "slurm_node_gres_detail_*"  # Detailed GRES info
        skip_timing_metrics: true
    
    cardinality:
      max_labels: 2000
      sample_rate: 1.0
    
    custom_labels:
      cluster_name: "main-cluster"
      environment: "production"

  partitions:
    enabled: true
    collection_interval: 120s
    timeout: 30s
    max_age: 1200s
    
    filters:
      metric_filter:
        enable_all: true
    
    custom_labels:
      cluster_name: "main-cluster"
      environment: "production"

  system:
    enabled: true
    collection_interval: 60s
    timeout: 30s
    
    custom_labels:
      cluster_name: "main-cluster"
      environment: "production"

  performance:
    enabled: true
    collection_interval: 30s
    
    custom_labels:
      instance: "${HOSTNAME}"
      environment: "production"

# Performance optimization for production
performance:
  memory_optimizer:
    enabled: true
    gc_percent: 100
    memory_limit: 512MB
    cleanup_interval: 300s
    target_heap_size: 256MB
  
  connection_pool:
    enabled: true
    min_connections: 2
    max_connections: 10
    max_idle_time: 600s
    connection_ttl: 3600s
    health_check_interval: 60s
  
  caching:
    enabled: true
    default_ttl: 30s
    max_size: 1000
    cleanup_interval: 300s
    
    # Cache policies by data type
    policies:
      nodes: 60s      # Nodes change less frequently
      partitions: 120s # Partitions are relatively static
      jobs: 15s       # Jobs change frequently
  
  cardinality_optimizer:
    enabled: true
    max_cardinality: 50000
    sample_rate: 0.9
    cleanup_interval: 600s
    
    # Aggressive cardinality control
    emergency_mode:
      threshold: 80000
      sample_rate: 0.5
      disable_high_cardinality_collectors: true

# Health check configuration
health:
  enabled: true
  check_interval: 30s
  timeout: 10s
  
  checks:
    - name: "slurm_api"
      type: "http"
      endpoint: "${SLURM_REST_URL}/slurm/v0.0.44/ping"
      timeout: 5s
      headers:
        X-SLURM-USER-TOKEN: "${SLURM_JWT_TOKEN}"
      expected_status: 200
    
    - name: "memory_usage"
      type: "memory"
      threshold: 80  # Alert if memory usage > 80%
    
    - name: "collection_errors"
      type: "error_rate"
      threshold: 5.0  # Alert if error rate > 5%
      window: 300s
    
    - name: "cardinality_check"
      type: "cardinality"
      threshold: 45000  # Alert if cardinality > 45k
    
    - name: "response_time"
      type: "response_time"
      threshold: 10s  # Alert if response time > 10s

# Security configuration
security:
  # Authentication
  authentication:
    enabled: false  # Handled by ingress/proxy
    type: "none"
  
  # Rate limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    burst_size: 100
    
    # IP-based rate limiting
    by_ip:
      enabled: true
      requests_per_minute: 60
  
  # Request validation
  validation:
    max_request_size: 1MB
    allowed_methods: ["GET", "HEAD"]
    allowed_paths:
      - "/metrics"
      - "/health"
      - "/ready"
  
  # Security headers
  headers:
    x_content_type_options: "nosniff"
    x_frame_options: "DENY"
    x_xss_protection: "1; mode=block"
    referrer_policy: "strict-origin-when-cross-origin"

# Monitoring and observability
monitoring:
  # Prometheus integration
  prometheus:
    enabled: true
    namespace: "slurm_exporter"
    subsystem: "production"
    
    # Custom metrics
    custom_metrics:
      - name: "build_info"
        help: "Build information"
        type: "gauge"
        labels:
          version: "${VERSION}"
          environment: "production"
          cluster: "main-cluster"
  
  # Tracing
  tracing:
    enabled: false  # Can be enabled for debugging
    jaeger_endpoint: "http://jaeger-collector:14268/api/traces"
    sample_rate: 0.01

# Production-specific features
features:
  # Configuration validation
  config_validation:
    enabled: true
    strict_mode: true
  
  # Hot configuration reload
  hot_reload:
    enabled: true
    watch_interval: 30s
    config_paths:
      - "/etc/slurm-exporter/config.yaml"
      - "/etc/slurm-exporter/collectors.yaml"
  
  # Graceful shutdown
  graceful_shutdown:
    enabled: true
    timeout: 30s
    drain_timeout: 15s
  
  # Circuit breaker for SLURM API
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30s
    half_open_max_calls: 3

# Resource limits and quotas
resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
    ephemeral_storage: "2Gi"
  
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeral_storage: "100Mi"
  
  # JVM-style heap management
  heap:
    initial_size: "128Mi"
    max_size: "512Mi"
    
# Environment-specific overrides
overrides:
  # High availability configuration
  high_availability:
    enabled: true
    min_replicas: 3
    max_replicas: 10
    
    # Anti-affinity for pod distribution
    anti_affinity:
      enabled: true
      topology_key: "kubernetes.io/hostname"
      required: false  # Preferred anti-affinity
  
  # Backup and disaster recovery
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention: "30d"
    
    # Configuration backup
    config_backup:
      enabled: true
      s3_bucket: "slurm-exporter-config-backup"
      encryption: true
  
  # Compliance and auditing
  compliance:
    enabled: true
    audit_logging: true
    data_retention: "7y"  # 7 years for compliance
    encryption_at_rest: true
    encryption_in_transit: true
    
    # PCI/SOX compliance settings
    pci_compliance: false
    sox_compliance: true
    gdpr_compliance: true

# Integration settings
integrations:
  # Service mesh
  service_mesh:
    enabled: false  # Set to true if using Istio/Linkerd
    type: "istio"
    
  # External secrets management
  secrets_manager:
    enabled: false  # Set to true if using external secrets
    type: "vault"  # or "aws-secrets-manager", "azure-keyvault"
    
  # Log aggregation
  log_aggregation:
    enabled: true
    type: "fluentd"  # or "logstash", "vector"
    endpoint: "fluentd.logging:24224"
    
  # Metrics aggregation
  metrics_aggregation:
    enabled: true
    federation:
      enabled: true
      scrape_interval: "30s"