apiVersion: v1
kind: ServiceAccount
metadata:
  name: slurm-exporter
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: serviceaccount
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/slurm-exporter-role
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slurm-exporter
  labels:
    app: slurm-exporter
    component: rbac
rules:
# Read access to nodes for node discovery
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Read access to pods for self-discovery
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# Read access to services for service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list"]
# Read access to configmaps for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Minimal access to secrets for credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["slurm-credentials"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slurm-exporter
  labels:
    app: slurm-exporter
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: slurm-exporter
subjects:
- kind: ServiceAccount
  name: slurm-exporter
  namespace: slurm-exporter

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: slurm-exporter
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: rbac
rules:
# Full access to own namespace resources
- apiGroups: [""]
  resources: ["configmaps", "secrets", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Access to pod logs for troubleshooting
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
# Access to metrics and monitoring
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slurm-exporter
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: slurm-exporter
subjects:
- kind: ServiceAccount
  name: slurm-exporter
  namespace: slurm-exporter