# Secrets Management and Security for SLURM Exporter
# This file implements comprehensive secrets security and management

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: secrets-management
  annotations:
    # External secrets operator integration
    secrets.kubernetes.io/managed-by: "external-secrets-operator"
    # Vault integration
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "slurm-exporter"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-manager
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: secrets-management
rules:
# Minimal secrets access
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames: 
  - "slurm-credentials"
  - "backup-encryption"
  - "tls-certificates"
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-manager
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: secrets-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-manager
subjects:
- kind: ServiceAccount
  name: secrets-manager
  namespace: slurm-exporter

---
# Secure secrets with rotation and encryption
apiVersion: v1
kind: Secret
metadata:
  name: slurm-credentials-secure
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: secrets
    encryption-level: high
    rotation-enabled: "true"
  annotations:
    secrets.kubernetes.io/created-by: "secrets-manager"
    secrets.kubernetes.io/rotation-schedule: "0 0 1 * *"  # Monthly rotation
    secrets.kubernetes.io/last-rotation: "2024-01-01T00:00:00Z"
    secrets.kubernetes.io/expiry-warning-days: "7"
    # Encryption at rest configuration
    encryption.kubernetes.io/provider: "aes-cbc"
    encryption.kubernetes.io/key-id: "slurm-exporter-key-2024"
    # Audit logging
    audit.kubernetes.io/access-logging: "enabled"
    audit.kubernetes.io/modification-logging: "enabled"
type: Opaque
data:
  # Base64 encoded and encrypted values
  rest-url: ""           # To be populated by secrets management system
  auth-type: ""          # To be populated by secrets management system
  jwt-token: ""          # To be populated by secrets management system
  api-key: ""            # To be populated by secrets management system
  username: ""           # To be populated by secrets management system
  password: ""           # To be populated by secrets management system
  
  # Additional security fields
  token-expiry: ""       # Token expiration timestamp
  rotation-key: ""       # Key for validating rotations
  checksum: ""           # Integrity checksum

---
# External Secrets Operator configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "slurm-exporter"
          serviceAccountRef:
            name: "secrets-manager"
      caBundle: |
        -----BEGIN CERTIFICATE-----
        # Vault CA certificate
        -----END CERTIFICATE-----

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slurm-credentials-external
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: external-secrets
spec:
  refreshInterval: 3600s  # Refresh every hour
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  
  target:
    name: slurm-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
        annotations:
          secrets.kubernetes.io/last-refresh: "{{ now | unixEpoch }}"
      data:
        rest-url: "{{ .rest_url | toString }}"
        auth-type: "{{ .auth_type | toString }}"
        jwt-token: "{{ .jwt_token | toString }}"
        api-key: "{{ .api_key | toString }}"
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
  
  data:
  - secretKey: rest_url
    remoteRef:
      key: slurm/exporter
      property: rest_url
  - secretKey: auth_type
    remoteRef:
      key: slurm/exporter
      property: auth_type
  - secretKey: jwt_token
    remoteRef:
      key: slurm/exporter
      property: jwt_token
  - secretKey: api_key
    remoteRef:
      key: slurm/exporter
      property: api_key
  - secretKey: username
    remoteRef:
      key: slurm/exporter
      property: username
  - secretKey: password
    remoteRef:
      key: slurm/exporter
      property: password

---
# Sealed Secrets configuration (alternative to External Secrets)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slurm-credentials-sealed
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: sealed-secrets
spec:
  encryptedData:
    # These would be encrypted by kubeseal
    rest-url: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
    auth-type: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
    jwt-token: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
    api-key: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
    username: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
    password: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
  template:
    metadata:
      name: slurm-credentials
      namespace: slurm-exporter
      labels:
        managed-by: sealed-secrets
    type: Opaque

---
# Encryption at rest configuration
apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: encryption
    key-rotation: enabled
  annotations:
    encryption.kubernetes.io/key-type: "aes-256-gcm"
    encryption.kubernetes.io/created: "2024-01-01T00:00:00Z"
    encryption.kubernetes.io/expires: "2024-12-31T23:59:59Z"
type: Opaque
data:
  # Encryption keys for different purposes
  backup-encryption-key: ""      # For backup encryption
  config-encryption-key: ""      # For configuration encryption
  log-encryption-key: ""         # For log encryption
  certificate-key: ""            # For certificate encryption
  
  # Key derivation parameters
  salt: ""                       # Cryptographic salt
  iv: ""                         # Initialization vector
  key-version: ""                # Key version for rotation

---
# Certificate management with cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slurm-exporter-tls
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: certificates
spec:
  secretName: slurm-exporter-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  
  dnsNames:
  - slurm-exporter.example.com
  - slurm-metrics.example.com
  - api.slurm-exporter.example.com
  
  # Certificate rotation
  duration: 2160h    # 90 days
  renewBefore: 360h  # 15 days before expiry
  
  # Key properties
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  
  # Subject configuration
  subject:
    organizations:
    - "Example Organization"
    organizationalUnits:
    - "IT Department"
    countries:
    - "US"
    localities:
    - "San Francisco"
    provinces:
    - "CA"
  
  # Additional security
  isCA: false
  keyUsages:
  - digital signature
  - key encipherment
  - server auth
  
  # Certificate transparency
  enableCertificateTransparency: true

---
# Secrets rotation automation
apiVersion: batch/v1
kind: CronJob
metadata:
  name: secrets-rotation
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: secrets-rotation
spec:
  schedule: "0 2 1 * *"  # Monthly on 1st day at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: slurm-exporter
            component: secrets-rotation
        spec:
          restartPolicy: Never
          serviceAccountName: secrets-manager
          
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            fsGroup: 65534
          
          containers:
          - name: secrets-rotator
            image: hashicorp/vault:latest
            imagePullPolicy: IfNotPresent
            
            securityContext:
              runAsNonRoot: true
              runAsUser: 65534
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            
            env:
            - name: VAULT_ADDR
              value: "https://vault.example.com"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token
                  key: token
            - name: SLACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: secrets-notifications
                  key: slack-webhook
            
            command:
            - /bin/sh
            - -c
            - |
              set -e
              
              echo "Starting secrets rotation process"
              
              # Function to send notifications
              send_notification() {
                local message="$1"
                local status="$2"
                
                if [ "$status" = "error" ]; then
                  emoji=":x:"
                  color="danger"
                else
                  emoji=":key:"
                  color="good"
                fi
                
                curl -X POST "$SLACK_WEBHOOK" \
                  -H 'Content-type: application/json' \
                  --data "{
                    \"attachments\": [{
                      \"color\": \"$color\",
                      \"text\": \"$emoji SLURM Exporter Secrets Rotation\\n$message\"
                    }]
                  }" || true
              }
              
              # Check if rotation is needed
              CURRENT_DATE=$(date +%s)
              LAST_ROTATION=$(kubectl get secret slurm-credentials \
                -o jsonpath='{.metadata.annotations.secrets\.kubernetes\.io/last-rotation}' || echo "0")
              
              if [ -z "$LAST_ROTATION" ]; then
                LAST_ROTATION="0"
              fi
              
              LAST_ROTATION_DATE=$(date -d "$LAST_ROTATION" +%s 2>/dev/null || echo "0")
              DAYS_SINCE_ROTATION=$(( (CURRENT_DATE - LAST_ROTATION_DATE) / 86400 ))
              
              echo "Days since last rotation: $DAYS_SINCE_ROTATION"
              
              if [ "$DAYS_SINCE_ROTATION" -lt 30 ]; then
                echo "Rotation not needed yet (last rotation: $DAYS_SINCE_ROTATION days ago)"
                send_notification "Secrets rotation check completed - no rotation needed" "info"
                exit 0
              fi
              
              echo "Starting secrets rotation (last rotation: $DAYS_SINCE_ROTATION days ago)"
              
              # Generate new SLURM JWT token
              echo "Generating new SLURM JWT token..."
              NEW_JWT_TOKEN=$(vault write -field=token auth/slurm/token \
                username=slurm-exporter \
                ttl=2160h)  # 90 days
              
              if [ -z "$NEW_JWT_TOKEN" ]; then
                echo "Failed to generate new JWT token"
                send_notification "Failed to generate new JWT token" "error"
                exit 1
              fi
              
              # Generate new API key if using API key auth
              echo "Generating new API key..."
              NEW_API_KEY=$(vault write -field=api_key auth/slurm/api-key \
                username=slurm-exporter \
                ttl=2160h)  # 90 days
              
              # Update secret with new credentials
              echo "Updating Kubernetes secret..."
              kubectl patch secret slurm-credentials -p "{
                \"data\": {
                  \"jwt-token\": \"$(echo -n "$NEW_JWT_TOKEN" | base64 -w 0)\",
                  \"api-key\": \"$(echo -n "$NEW_API_KEY" | base64 -w 0)\"
                },
                \"metadata\": {
                  \"annotations\": {
                    \"secrets.kubernetes.io/last-rotation\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
                  }
                }
              }"
              
              # Restart deployment to pick up new credentials
              echo "Restarting SLURM Exporter deployment..."
              kubectl rollout restart deployment/slurm-exporter
              
              # Wait for rollout to complete
              kubectl rollout status deployment/slurm-exporter --timeout=300s
              
              # Verify new credentials work
              echo "Verifying new credentials..."
              POD_NAME=$(kubectl get pods -l app=slurm-exporter -o jsonpath='{.items[0].metadata.name}')
              
              if kubectl exec "$POD_NAME" -- curl -f -s \
                  -H "X-SLURM-USER-TOKEN: $NEW_JWT_TOKEN" \
                  "$SLURM_REST_URL/slurm/v0.0.44/ping" > /dev/null; then
                echo "New credentials verified successfully"
                send_notification "Secrets rotation completed successfully" "success"
              else
                echo "New credentials verification failed"
                send_notification "Secrets rotation completed but verification failed" "error"
                exit 1
              fi
              
              echo "Secrets rotation completed successfully"
            
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            
            volumeMounts:
            - name: tmp
              mountPath: /tmp
          
          volumes:
          - name: tmp
            emptyDir:
              sizeLimit: 100Mi

---
# Secrets access monitoring
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: secrets-security-alerts
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: secrets-security
spec:
  groups:
  - name: secrets-security
    rules:
    - alert: SecretsRotationOverdue
      expr: (time() - kube_secret_info{secret="slurm-credentials", namespace="slurm-exporter"}) > 2678400  # 31 days
      for: 0m
      labels:
        severity: warning
        component: secrets-management
      annotations:
        summary: "Secrets rotation overdue"
        description: "SLURM credentials have not been rotated in over 31 days"
        action: "Run secrets rotation job or investigate rotation failure"
    
    - alert: SecretsAccessAnomaly
      expr: increase(apiserver_audit_total{verb="get", objectRef_resource="secrets", objectRef_name="slurm-credentials"}[1h]) > 100
      for: 5m
      labels:
        severity: warning
        component: secrets-security
      annotations:
        summary: "Unusual secrets access pattern"
        description: "High frequency access to SLURM credentials detected"
        action: "Investigate unusual access patterns"
    
    - alert: SecretsRotationFailed
      expr: kube_job_status_failed{job_name=~"secrets-rotation.*"} > 0
      for: 0m
      labels:
        severity: critical
        component: secrets-management
      annotations:
        summary: "Secrets rotation job failed"
        description: "Secrets rotation job has failed"
        action: "Investigate rotation failure and perform manual rotation if needed"
    
    - alert: CertificateExpiringSoon
      expr: (cert_manager_certificate_expiration_timestamp_seconds - time()) / 86400 < 7
      for: 0m
      labels:
        severity: warning
        component: certificate-management
      annotations:
        summary: "Certificate expiring soon"
        description: "TLS certificate expires in less than 7 days"
        action: "Check certificate renewal process"

---
# Security scanning for secrets
apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-security-policy
  namespace: slurm-exporter
  labels:
    app: slurm-exporter
    component: secrets-security
data:
  security-policy.yaml: |
    # Secrets Security Policy
    secrets_security:
      # Access control
      access_control:
        - principle: "least_privilege"
          description: "Grant minimum required access to secrets"
          enforcement: "RBAC with specific resource names"
        
        - principle: "segregation_of_duties"
          description: "Separate secrets management from application operations"
          enforcement: "Different service accounts for different roles"
        
        - principle: "audit_logging"
          description: "Log all secrets access and modifications"
          enforcement: "Kubernetes audit policy and monitoring"
      
      # Encryption requirements
      encryption:
        - requirement: "encryption_at_rest"
          description: "All secrets must be encrypted at rest"
          implementation: "Kubernetes etcd encryption + external KMS"
        
        - requirement: "encryption_in_transit"
          description: "All secrets must be encrypted in transit"
          implementation: "TLS 1.3 for all communications"
        
        - requirement: "key_rotation"
          description: "Encryption keys must be rotated regularly"
          schedule: "Every 90 days"
      
      # Lifecycle management
      lifecycle:
        - stage: "creation"
          requirements: ["strong_entropy", "secure_generation", "immediate_encryption"]
        
        - stage: "storage"
          requirements: ["encrypted_at_rest", "access_controlled", "audit_logged"]
        
        - stage: "usage"
          requirements: ["encrypted_in_transit", "minimal_exposure", "secure_injection"]
        
        - stage: "rotation"
          requirements: ["automated_rotation", "graceful_transition", "verification"]
        
        - stage: "deletion"
          requirements: ["secure_deletion", "audit_trail", "verification"]
      
      # Compliance requirements
      compliance:
        - standard: "SOC2"
          requirements: ["access_controls", "encryption", "audit_logging", "change_management"]
        
        - standard: "PCI_DSS"
          requirements: ["key_management", "secure_transmission", "access_restrictions"]
        
        - standard: "GDPR"
          requirements: ["data_protection", "access_controls", "deletion_procedures"]