// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/jontk/slurm-client/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// MockSlurmClientInterface is an autogenerated mock type for the SlurmClient type
type MockSlurmClientInterface struct {
	mock.Mock
}

// Accounts provides a mock function with no fields
func (_m *MockSlurmClientInterface) Accounts() interfaces.AccountManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Accounts")
	}

	var r0 interfaces.AccountManager
	if rf, ok := ret.Get(0).(func() interfaces.AccountManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.AccountManager)
		}
	}

	return r0
}

// Associations provides a mock function with no fields
func (_m *MockSlurmClientInterface) Associations() interfaces.AssociationManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Associations")
	}

	var r0 interfaces.AssociationManager
	if rf, ok := ret.Get(0).(func() interfaces.AssociationManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.AssociationManager)
		}
	}

	return r0
}

// Close provides a mock function with no fields
func (_m *MockSlurmClientInterface) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Clusters provides a mock function with no fields
func (_m *MockSlurmClientInterface) Clusters() interfaces.ClusterManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clusters")
	}

	var r0 interfaces.ClusterManager
	if rf, ok := ret.Get(0).(func() interfaces.ClusterManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.ClusterManager)
		}
	}

	return r0
}

// CreateTRES provides a mock function with given fields: ctx, req
func (_m *MockSlurmClientInterface) CreateTRES(ctx context.Context, req *interfaces.CreateTRESRequest) (*interfaces.TRES, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTRES")
	}

	var r0 *interfaces.TRES
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.CreateTRESRequest) (*interfaces.TRES, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.CreateTRESRequest) *interfaces.TRES); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.TRES)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.CreateTRESRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfig provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetConfig(ctx context.Context) (*interfaces.Config, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *interfaces.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*interfaces.Config, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *interfaces.Config); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDBDiagnostics provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetDBDiagnostics(ctx context.Context) (*interfaces.Diagnostics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDBDiagnostics")
	}

	var r0 *interfaces.Diagnostics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*interfaces.Diagnostics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *interfaces.Diagnostics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Diagnostics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDiagnostics provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetDiagnostics(ctx context.Context) (*interfaces.Diagnostics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDiagnostics")
	}

	var r0 *interfaces.Diagnostics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*interfaces.Diagnostics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *interfaces.Diagnostics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Diagnostics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstance provides a mock function with given fields: ctx, opts
func (_m *MockSlurmClientInterface) GetInstance(ctx context.Context, opts *interfaces.GetInstanceOptions) (*interfaces.Instance, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *interfaces.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.GetInstanceOptions) (*interfaces.Instance, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.GetInstanceOptions) *interfaces.Instance); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.GetInstanceOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstances provides a mock function with given fields: ctx, opts
func (_m *MockSlurmClientInterface) GetInstances(ctx context.Context, opts *interfaces.GetInstancesOptions) (*interfaces.InstanceList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetInstances")
	}

	var r0 *interfaces.InstanceList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.GetInstancesOptions) (*interfaces.InstanceList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.GetInstancesOptions) *interfaces.InstanceList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.InstanceList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.GetInstancesOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLicenses provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetLicenses(ctx context.Context) (*interfaces.LicenseList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLicenses")
	}

	var r0 *interfaces.LicenseList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*interfaces.LicenseList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *interfaces.LicenseList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.LicenseList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShares provides a mock function with given fields: ctx, opts
func (_m *MockSlurmClientInterface) GetShares(ctx context.Context, opts *interfaces.GetSharesOptions) (*interfaces.SharesList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetShares")
	}

	var r0 *interfaces.SharesList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.GetSharesOptions) (*interfaces.SharesList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.GetSharesOptions) *interfaces.SharesList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.SharesList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.GetSharesOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTRES provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetTRES(ctx context.Context) (*interfaces.TRESList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTRES")
	}

	var r0 *interfaces.TRESList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*interfaces.TRESList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *interfaces.TRESList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.TRESList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Info provides a mock function with no fields
func (_m *MockSlurmClientInterface) Info() interfaces.InfoManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 interfaces.InfoManager
	if rf, ok := ret.Get(0).(func() interfaces.InfoManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.InfoManager)
		}
	}

	return r0
}

// Jobs provides a mock function with no fields
func (_m *MockSlurmClientInterface) Jobs() interfaces.JobManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Jobs")
	}

	var r0 interfaces.JobManager
	if rf, ok := ret.Get(0).(func() interfaces.JobManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.JobManager)
		}
	}

	return r0
}

// Nodes provides a mock function with no fields
func (_m *MockSlurmClientInterface) Nodes() interfaces.NodeManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Nodes")
	}

	var r0 interfaces.NodeManager
	if rf, ok := ret.Get(0).(func() interfaces.NodeManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.NodeManager)
		}
	}

	return r0
}

// Partitions provides a mock function with no fields
func (_m *MockSlurmClientInterface) Partitions() interfaces.PartitionManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Partitions")
	}

	var r0 interfaces.PartitionManager
	if rf, ok := ret.Get(0).(func() interfaces.PartitionManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.PartitionManager)
		}
	}

	return r0
}

// QoS provides a mock function with no fields
func (_m *MockSlurmClientInterface) QoS() interfaces.QoSManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for QoS")
	}

	var r0 interfaces.QoSManager
	if rf, ok := ret.Get(0).(func() interfaces.QoSManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.QoSManager)
		}
	}

	return r0
}

// Reconfigure provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) Reconfigure(ctx context.Context) (*interfaces.ReconfigureResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reconfigure")
	}

	var r0 *interfaces.ReconfigureResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*interfaces.ReconfigureResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *interfaces.ReconfigureResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ReconfigureResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reservations provides a mock function with no fields
func (_m *MockSlurmClientInterface) Reservations() interfaces.ReservationManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reservations")
	}

	var r0 interfaces.ReservationManager
	if rf, ok := ret.Get(0).(func() interfaces.ReservationManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.ReservationManager)
		}
	}

	return r0
}

// Users provides a mock function with no fields
func (_m *MockSlurmClientInterface) Users() interfaces.UserManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 interfaces.UserManager
	if rf, ok := ret.Get(0).(func() interfaces.UserManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.UserManager)
		}
	}

	return r0
}

// Version provides a mock function with no fields
func (_m *MockSlurmClientInterface) Version() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// WCKeys provides a mock function with no fields
func (_m *MockSlurmClientInterface) WCKeys() interfaces.WCKeyManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WCKeys")
	}

	var r0 interfaces.WCKeyManager
	if rf, ok := ret.Get(0).(func() interfaces.WCKeyManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.WCKeyManager)
		}
	}

	return r0
}

// NewMockSlurmClientInterface creates a new instance of MockSlurmClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlurmClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlurmClientInterface {
	mock := &MockSlurmClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
