// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/jontk/slurm-client/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// MockJobManager is an autogenerated mock type for the JobManager type
type MockJobManager struct {
	mock.Mock
}

// Allocate provides a mock function with given fields: ctx, req
func (_m *MockJobManager) Allocate(ctx context.Context, req *interfaces.JobAllocateRequest) (*interfaces.JobAllocateResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Allocate")
	}

	var r0 *interfaces.JobAllocateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.JobAllocateRequest) (*interfaces.JobAllocateResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.JobAllocateRequest) *interfaces.JobAllocateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobAllocateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.JobAllocateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyzeBatchJobs provides a mock function with given fields: ctx, jobIDs, opts
func (_m *MockJobManager) AnalyzeBatchJobs(ctx context.Context, jobIDs []string, opts *interfaces.BatchAnalysisOptions) (*interfaces.BatchJobAnalysis, error) {
	ret := _m.Called(ctx, jobIDs, opts)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeBatchJobs")
	}

	var r0 *interfaces.BatchJobAnalysis
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, *interfaces.BatchAnalysisOptions) (*interfaces.BatchJobAnalysis, error)); ok {
		return rf(ctx, jobIDs, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, *interfaces.BatchAnalysisOptions) *interfaces.BatchJobAnalysis); ok {
		r0 = rf(ctx, jobIDs, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.BatchJobAnalysis)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, *interfaces.BatchAnalysisOptions) error); ok {
		r1 = rf(ctx, jobIDs, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cancel provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) Cancel(ctx context.Context, jobID string) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateEfficiencyReport provides a mock function with given fields: ctx, opts
func (_m *MockJobManager) GenerateEfficiencyReport(ctx context.Context, opts *interfaces.ReportOptions) (*interfaces.EfficiencyReport, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GenerateEfficiencyReport")
	}

	var r0 *interfaces.EfficiencyReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ReportOptions) (*interfaces.EfficiencyReport, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ReportOptions) *interfaces.EfficiencyReport); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.EfficiencyReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.ReportOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) Get(ctx context.Context, jobID string) (*interfaces.Job, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *interfaces.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.Job, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.Job); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobCPUAnalytics provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) GetJobCPUAnalytics(ctx context.Context, jobID string) (*interfaces.CPUAnalytics, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobCPUAnalytics")
	}

	var r0 *interfaces.CPUAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.CPUAnalytics, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.CPUAnalytics); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.CPUAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobComprehensiveAnalytics provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) GetJobComprehensiveAnalytics(ctx context.Context, jobID string) (*interfaces.JobComprehensiveAnalytics, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobComprehensiveAnalytics")
	}

	var r0 *interfaces.JobComprehensiveAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.JobComprehensiveAnalytics, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.JobComprehensiveAnalytics); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobComprehensiveAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobEfficiency provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) GetJobEfficiency(ctx context.Context, jobID string) (*interfaces.ResourceUtilization, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobEfficiency")
	}

	var r0 *interfaces.ResourceUtilization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.ResourceUtilization, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.ResourceUtilization); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ResourceUtilization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobIOAnalytics provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) GetJobIOAnalytics(ctx context.Context, jobID string) (*interfaces.IOAnalytics, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobIOAnalytics")
	}

	var r0 *interfaces.IOAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.IOAnalytics, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.IOAnalytics); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.IOAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobLiveMetrics provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) GetJobLiveMetrics(ctx context.Context, jobID string) (*interfaces.JobLiveMetrics, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobLiveMetrics")
	}

	var r0 *interfaces.JobLiveMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.JobLiveMetrics, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.JobLiveMetrics); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobLiveMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobMemoryAnalytics provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) GetJobMemoryAnalytics(ctx context.Context, jobID string) (*interfaces.MemoryAnalytics, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobMemoryAnalytics")
	}

	var r0 *interfaces.MemoryAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.MemoryAnalytics, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.MemoryAnalytics); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.MemoryAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobPerformance provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) GetJobPerformance(ctx context.Context, jobID string) (*interfaces.JobPerformance, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobPerformance")
	}

	var r0 *interfaces.JobPerformance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.JobPerformance, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.JobPerformance); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobPerformance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobPerformanceHistory provides a mock function with given fields: ctx, jobID, opts
func (_m *MockJobManager) GetJobPerformanceHistory(ctx context.Context, jobID string, opts *interfaces.PerformanceHistoryOptions) (*interfaces.JobPerformanceHistory, error) {
	ret := _m.Called(ctx, jobID, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetJobPerformanceHistory")
	}

	var r0 *interfaces.JobPerformanceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.PerformanceHistoryOptions) (*interfaces.JobPerformanceHistory, error)); ok {
		return rf(ctx, jobID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.PerformanceHistoryOptions) *interfaces.JobPerformanceHistory); ok {
		r0 = rf(ctx, jobID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobPerformanceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *interfaces.PerformanceHistoryOptions) error); ok {
		r1 = rf(ctx, jobID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobResourceTrends provides a mock function with given fields: ctx, jobID, opts
func (_m *MockJobManager) GetJobResourceTrends(ctx context.Context, jobID string, opts *interfaces.ResourceTrendsOptions) (*interfaces.JobResourceTrends, error) {
	ret := _m.Called(ctx, jobID, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetJobResourceTrends")
	}

	var r0 *interfaces.JobResourceTrends
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.ResourceTrendsOptions) (*interfaces.JobResourceTrends, error)); ok {
		return rf(ctx, jobID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.ResourceTrendsOptions) *interfaces.JobResourceTrends); ok {
		r0 = rf(ctx, jobID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobResourceTrends)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *interfaces.ResourceTrendsOptions) error); ok {
		r1 = rf(ctx, jobID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobStepAPIData provides a mock function with given fields: ctx, jobID, stepID
func (_m *MockJobManager) GetJobStepAPIData(ctx context.Context, jobID string, stepID string) (*interfaces.JobStepAPIData, error) {
	ret := _m.Called(ctx, jobID, stepID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobStepAPIData")
	}

	var r0 *interfaces.JobStepAPIData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*interfaces.JobStepAPIData, error)); ok {
		return rf(ctx, jobID, stepID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *interfaces.JobStepAPIData); ok {
		r0 = rf(ctx, jobID, stepID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobStepAPIData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, jobID, stepID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobStepDetails provides a mock function with given fields: ctx, jobID, stepID
func (_m *MockJobManager) GetJobStepDetails(ctx context.Context, jobID string, stepID string) (*interfaces.JobStepDetails, error) {
	ret := _m.Called(ctx, jobID, stepID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobStepDetails")
	}

	var r0 *interfaces.JobStepDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*interfaces.JobStepDetails, error)); ok {
		return rf(ctx, jobID, stepID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *interfaces.JobStepDetails); ok {
		r0 = rf(ctx, jobID, stepID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobStepDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, jobID, stepID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobStepUtilization provides a mock function with given fields: ctx, jobID, stepID
func (_m *MockJobManager) GetJobStepUtilization(ctx context.Context, jobID string, stepID string) (*interfaces.JobStepUtilization, error) {
	ret := _m.Called(ctx, jobID, stepID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobStepUtilization")
	}

	var r0 *interfaces.JobStepUtilization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*interfaces.JobStepUtilization, error)); ok {
		return rf(ctx, jobID, stepID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *interfaces.JobStepUtilization); ok {
		r0 = rf(ctx, jobID, stepID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobStepUtilization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, jobID, stepID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobStepsFromAccounting provides a mock function with given fields: ctx, jobID, opts
func (_m *MockJobManager) GetJobStepsFromAccounting(ctx context.Context, jobID string, opts *interfaces.AccountingQueryOptions) (*interfaces.AccountingJobSteps, error) {
	ret := _m.Called(ctx, jobID, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetJobStepsFromAccounting")
	}

	var r0 *interfaces.AccountingJobSteps
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.AccountingQueryOptions) (*interfaces.AccountingJobSteps, error)); ok {
		return rf(ctx, jobID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.AccountingQueryOptions) *interfaces.AccountingJobSteps); ok {
		r0 = rf(ctx, jobID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.AccountingJobSteps)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *interfaces.AccountingQueryOptions) error); ok {
		r1 = rf(ctx, jobID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobUtilization provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) GetJobUtilization(ctx context.Context, jobID string) (*interfaces.JobUtilization, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobUtilization")
	}

	var r0 *interfaces.JobUtilization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.JobUtilization, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.JobUtilization); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobUtilization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPerformanceTrends provides a mock function with given fields: ctx, opts
func (_m *MockJobManager) GetPerformanceTrends(ctx context.Context, opts *interfaces.TrendAnalysisOptions) (*interfaces.PerformanceTrends, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetPerformanceTrends")
	}

	var r0 *interfaces.PerformanceTrends
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.TrendAnalysisOptions) (*interfaces.PerformanceTrends, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.TrendAnalysisOptions) *interfaces.PerformanceTrends); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.PerformanceTrends)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.TrendAnalysisOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStepAccountingData provides a mock function with given fields: ctx, jobID, stepID
func (_m *MockJobManager) GetStepAccountingData(ctx context.Context, jobID string, stepID string) (*interfaces.StepAccountingRecord, error) {
	ret := _m.Called(ctx, jobID, stepID)

	if len(ret) == 0 {
		panic("no return value specified for GetStepAccountingData")
	}

	var r0 *interfaces.StepAccountingRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*interfaces.StepAccountingRecord, error)); ok {
		return rf(ctx, jobID, stepID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *interfaces.StepAccountingRecord); ok {
		r0 = rf(ctx, jobID, stepID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.StepAccountingRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, jobID, stepID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserEfficiencyTrends provides a mock function with given fields: ctx, userID, opts
func (_m *MockJobManager) GetUserEfficiencyTrends(ctx context.Context, userID string, opts *interfaces.EfficiencyTrendOptions) (*interfaces.UserEfficiencyTrends, error) {
	ret := _m.Called(ctx, userID, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetUserEfficiencyTrends")
	}

	var r0 *interfaces.UserEfficiencyTrends
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.EfficiencyTrendOptions) (*interfaces.UserEfficiencyTrends, error)); ok {
		return rf(ctx, userID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.EfficiencyTrendOptions) *interfaces.UserEfficiencyTrends); ok {
		r0 = rf(ctx, userID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.UserEfficiencyTrends)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *interfaces.EfficiencyTrendOptions) error); ok {
		r1 = rf(ctx, userID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkflowPerformance provides a mock function with given fields: ctx, workflowID, opts
func (_m *MockJobManager) GetWorkflowPerformance(ctx context.Context, workflowID string, opts *interfaces.WorkflowAnalysisOptions) (*interfaces.WorkflowPerformance, error) {
	ret := _m.Called(ctx, workflowID, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowPerformance")
	}

	var r0 *interfaces.WorkflowPerformance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.WorkflowAnalysisOptions) (*interfaces.WorkflowPerformance, error)); ok {
		return rf(ctx, workflowID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.WorkflowAnalysisOptions) *interfaces.WorkflowPerformance); ok {
		r0 = rf(ctx, workflowID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.WorkflowPerformance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *interfaces.WorkflowAnalysisOptions) error); ok {
		r1 = rf(ctx, workflowID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hold provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) Hold(ctx context.Context, jobID string) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Hold")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockJobManager) List(ctx context.Context, opts *interfaces.ListJobsOptions) (*interfaces.JobList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *interfaces.JobList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ListJobsOptions) (*interfaces.JobList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ListJobsOptions) *interfaces.JobList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.ListJobsOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListJobStepsFromSacct provides a mock function with given fields: ctx, jobID, opts
func (_m *MockJobManager) ListJobStepsFromSacct(ctx context.Context, jobID string, opts *interfaces.SacctQueryOptions) (*interfaces.SacctJobStepData, error) {
	ret := _m.Called(ctx, jobID, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListJobStepsFromSacct")
	}

	var r0 *interfaces.SacctJobStepData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.SacctQueryOptions) (*interfaces.SacctJobStepData, error)); ok {
		return rf(ctx, jobID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.SacctQueryOptions) *interfaces.SacctJobStepData); ok {
		r0 = rf(ctx, jobID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.SacctJobStepData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *interfaces.SacctQueryOptions) error); ok {
		r1 = rf(ctx, jobID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListJobStepsWithMetrics provides a mock function with given fields: ctx, jobID, opts
func (_m *MockJobManager) ListJobStepsWithMetrics(ctx context.Context, jobID string, opts *interfaces.ListJobStepsOptions) (*interfaces.JobStepMetricsList, error) {
	ret := _m.Called(ctx, jobID, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListJobStepsWithMetrics")
	}

	var r0 *interfaces.JobStepMetricsList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.ListJobStepsOptions) (*interfaces.JobStepMetricsList, error)); ok {
		return rf(ctx, jobID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.ListJobStepsOptions) *interfaces.JobStepMetricsList); ok {
		r0 = rf(ctx, jobID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobStepMetricsList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *interfaces.ListJobStepsOptions) error); ok {
		r1 = rf(ctx, jobID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Notify provides a mock function with given fields: ctx, jobID, message
func (_m *MockJobManager) Notify(ctx context.Context, jobID string, message string) error {
	ret := _m.Called(ctx, jobID, message)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, jobID, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Release provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) Release(ctx context.Context, jobID string) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Requeue provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) Requeue(ctx context.Context, jobID string) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Requeue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Signal provides a mock function with given fields: ctx, jobID, signal
func (_m *MockJobManager) Signal(ctx context.Context, jobID string, signal string) error {
	ret := _m.Called(ctx, jobID, signal)

	if len(ret) == 0 {
		panic("no return value specified for Signal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, jobID, signal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Steps provides a mock function with given fields: ctx, jobID
func (_m *MockJobManager) Steps(ctx context.Context, jobID string) (*interfaces.JobStepList, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Steps")
	}

	var r0 *interfaces.JobStepList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.JobStepList, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.JobStepList); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobStepList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Submit provides a mock function with given fields: ctx, job
func (_m *MockJobManager) Submit(ctx context.Context, job *interfaces.JobSubmission) (*interfaces.JobSubmitResponse, error) {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 *interfaces.JobSubmitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.JobSubmission) (*interfaces.JobSubmitResponse, error)); ok {
		return rf(ctx, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.JobSubmission) *interfaces.JobSubmitResponse); ok {
		r0 = rf(ctx, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.JobSubmitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.JobSubmission) error); ok {
		r1 = rf(ctx, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, jobID, update
func (_m *MockJobManager) Update(ctx context.Context, jobID string, update *interfaces.JobUpdate) error {
	ret := _m.Called(ctx, jobID, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.JobUpdate) error); ok {
		r0 = rf(ctx, jobID, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *MockJobManager) Watch(ctx context.Context, opts *interfaces.WatchJobsOptions) (<-chan interfaces.JobEvent, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan interfaces.JobEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.WatchJobsOptions) (<-chan interfaces.JobEvent, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.WatchJobsOptions) <-chan interfaces.JobEvent); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan interfaces.JobEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.WatchJobsOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WatchJobMetrics provides a mock function with given fields: ctx, jobID, opts
func (_m *MockJobManager) WatchJobMetrics(ctx context.Context, jobID string, opts *interfaces.WatchMetricsOptions) (<-chan interfaces.JobMetricsEvent, error) {
	ret := _m.Called(ctx, jobID, opts)

	if len(ret) == 0 {
		panic("no return value specified for WatchJobMetrics")
	}

	var r0 <-chan interfaces.JobMetricsEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.WatchMetricsOptions) (<-chan interfaces.JobMetricsEvent, error)); ok {
		return rf(ctx, jobID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.WatchMetricsOptions) <-chan interfaces.JobMetricsEvent); ok {
		r0 = rf(ctx, jobID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan interfaces.JobMetricsEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *interfaces.WatchMetricsOptions) error); ok {
		r1 = rf(ctx, jobID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockJobManager creates a new instance of MockJobManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobManager {
	mock := &MockJobManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
