// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	performance "github.com/jontk/slurm-exporter/internal/performance"
	mock "github.com/stretchr/testify/mock"
)

// MockProfileStorage is an autogenerated mock type for the ProfileStorage type
type MockProfileStorage struct {
	mock.Mock
}

type MockProfileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileStorage) EXPECT() *MockProfileStorage_Expecter {
	return &MockProfileStorage_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with no fields
func (_m *MockProfileStorage) Cleanup() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProfileStorage_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockProfileStorage_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *MockProfileStorage_Expecter) Cleanup() *MockProfileStorage_Cleanup_Call {
	return &MockProfileStorage_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *MockProfileStorage_Cleanup_Call) Run(run func()) *MockProfileStorage_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProfileStorage_Cleanup_Call) Return(_a0 error) *MockProfileStorage_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileStorage_Cleanup_Call) RunAndReturn(run func() error) *MockProfileStorage_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockProfileStorage) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProfileStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProfileStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockProfileStorage_Expecter) Delete(id interface{}) *MockProfileStorage_Delete_Call {
	return &MockProfileStorage_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockProfileStorage_Delete_Call) Run(run func(id string)) *MockProfileStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockProfileStorage_Delete_Call) Return(_a0 error) *MockProfileStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileStorage_Delete_Call) RunAndReturn(run func(string) error) *MockProfileStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with no fields
func (_m *MockProfileStorage) GetStats() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockProfileStorage_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockProfileStorage_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *MockProfileStorage_Expecter) GetStats() *MockProfileStorage_GetStats_Call {
	return &MockProfileStorage_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *MockProfileStorage_GetStats_Call) Run(run func()) *MockProfileStorage_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProfileStorage_GetStats_Call) Return(_a0 map[string]interface{}) *MockProfileStorage_GetStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileStorage_GetStats_Call) RunAndReturn(run func() map[string]interface{}) *MockProfileStorage_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockProfileStorage) List() ([]*performance.ProfileMetadata, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*performance.ProfileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*performance.ProfileMetadata, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*performance.ProfileMetadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*performance.ProfileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProfileStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProfileStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockProfileStorage_Expecter) List() *MockProfileStorage_List_Call {
	return &MockProfileStorage_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockProfileStorage_List_Call) Run(run func()) *MockProfileStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProfileStorage_List_Call) Return(_a0 []*performance.ProfileMetadata, _a1 error) *MockProfileStorage_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProfileStorage_List_Call) RunAndReturn(run func() ([]*performance.ProfileMetadata, error)) *MockProfileStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: id
func (_m *MockProfileStorage) Load(id string) (*performance.CollectorProfile, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *performance.CollectorProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*performance.CollectorProfile, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *performance.CollectorProfile); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*performance.CollectorProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProfileStorage_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockProfileStorage_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - id string
func (_e *MockProfileStorage_Expecter) Load(id interface{}) *MockProfileStorage_Load_Call {
	return &MockProfileStorage_Load_Call{Call: _e.mock.On("Load", id)}
}

func (_c *MockProfileStorage_Load_Call) Run(run func(id string)) *MockProfileStorage_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockProfileStorage_Load_Call) Return(_a0 *performance.CollectorProfile, _a1 error) *MockProfileStorage_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProfileStorage_Load_Call) RunAndReturn(run func(string) (*performance.CollectorProfile, error)) *MockProfileStorage_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: profile
func (_m *MockProfileStorage) Save(profile *performance.CollectorProfile) error {
	ret := _m.Called(profile)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*performance.CollectorProfile) error); ok {
		r0 = rf(profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProfileStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockProfileStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - profile *performance.CollectorProfile
func (_e *MockProfileStorage_Expecter) Save(profile interface{}) *MockProfileStorage_Save_Call {
	return &MockProfileStorage_Save_Call{Call: _e.mock.On("Save", profile)}
}

func (_c *MockProfileStorage_Save_Call) Run(run func(profile *performance.CollectorProfile)) *MockProfileStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*performance.CollectorProfile))
	})
	return _c
}

func (_c *MockProfileStorage_Save_Call) Return(_a0 error) *MockProfileStorage_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileStorage_Save_Call) RunAndReturn(run func(*performance.CollectorProfile) error) *MockProfileStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileStorage creates a new instance of MockProfileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileStorage {
	mock := &MockProfileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
