// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/jontk/slurm-client"
	mock "github.com/stretchr/testify/mock"
)

// MockNodeManager is an autogenerated mock type for the NodeManager type
type MockNodeManager struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, nodeName
func (_m *MockNodeManager) Delete(ctx context.Context, nodeName string) error {
	ret := _m.Called(ctx, nodeName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, nodeName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Drain provides a mock function with given fields: ctx, nodeName, reason
func (_m *MockNodeManager) Drain(ctx context.Context, nodeName string, reason string) error {
	ret := _m.Called(ctx, nodeName, reason)

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, nodeName, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, nodeName
func (_m *MockNodeManager) Get(ctx context.Context, nodeName string) (*slurm.Node, error) {
	ret := _m.Called(ctx, nodeName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *slurm.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*slurm.Node, error)); ok {
		return rf(ctx, nodeName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *slurm.Node); ok {
		r0 = rf(ctx, nodeName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nodeName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockNodeManager) List(ctx context.Context, opts *slurm.ListNodesOptions) (*slurm.NodeList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *slurm.NodeList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.ListNodesOptions) (*slurm.NodeList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.ListNodesOptions) *slurm.NodeList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.NodeList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.ListNodesOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resume provides a mock function with given fields: ctx, nodeName
func (_m *MockNodeManager) Resume(ctx context.Context, nodeName string) error {
	ret := _m.Called(ctx, nodeName)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, nodeName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, nodeName, update
func (_m *MockNodeManager) Update(ctx context.Context, nodeName string, update *slurm.NodeUpdate) error {
	ret := _m.Called(ctx, nodeName, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *slurm.NodeUpdate) error); ok {
		r0 = rf(ctx, nodeName, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *MockNodeManager) Watch(ctx context.Context, opts *slurm.WatchNodesOptions) (<-chan slurm.NodeEvent, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan slurm.NodeEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.WatchNodesOptions) (<-chan slurm.NodeEvent, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.WatchNodesOptions) <-chan slurm.NodeEvent); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan slurm.NodeEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.WatchNodesOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockNodeManager creates a new instance of MockNodeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeManager {
	mock := &MockNodeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
