// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/jontk/slurm-client/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// MockPartitionManager is an autogenerated mock type for the PartitionManager type
type MockPartitionManager struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, partition
func (_m *MockPartitionManager) Create(ctx context.Context, partition *interfaces.PartitionCreate) (*interfaces.PartitionCreateResponse, error) {
	ret := _m.Called(ctx, partition)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *interfaces.PartitionCreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.PartitionCreate) (*interfaces.PartitionCreateResponse, error)); ok {
		return rf(ctx, partition)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.PartitionCreate) *interfaces.PartitionCreateResponse); ok {
		r0 = rf(ctx, partition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.PartitionCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.PartitionCreate) error); ok {
		r1 = rf(ctx, partition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, partitionName
func (_m *MockPartitionManager) Delete(ctx context.Context, partitionName string) error {
	ret := _m.Called(ctx, partitionName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, partitionName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, partitionName
func (_m *MockPartitionManager) Get(ctx context.Context, partitionName string) (*interfaces.Partition, error) {
	ret := _m.Called(ctx, partitionName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *interfaces.Partition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.Partition, error)); ok {
		return rf(ctx, partitionName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.Partition); ok {
		r0 = rf(ctx, partitionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Partition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partitionName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockPartitionManager) List(ctx context.Context, opts *interfaces.ListPartitionsOptions) (*interfaces.PartitionList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *interfaces.PartitionList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ListPartitionsOptions) (*interfaces.PartitionList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ListPartitionsOptions) *interfaces.PartitionList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.PartitionList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.ListPartitionsOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, partitionName, update
func (_m *MockPartitionManager) Update(ctx context.Context, partitionName string, update *interfaces.PartitionUpdate) error {
	ret := _m.Called(ctx, partitionName, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.PartitionUpdate) error); ok {
		r0 = rf(ctx, partitionName, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *MockPartitionManager) Watch(ctx context.Context, opts *interfaces.WatchPartitionsOptions) (<-chan interfaces.PartitionEvent, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan interfaces.PartitionEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.WatchPartitionsOptions) (<-chan interfaces.PartitionEvent, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.WatchPartitionsOptions) <-chan interfaces.PartitionEvent); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan interfaces.PartitionEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.WatchPartitionsOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPartitionManager creates a new instance of MockPartitionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPartitionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPartitionManager {
	mock := &MockPartitionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
