// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/jontk/slurm-client/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// MockClusterManager is an autogenerated mock type for the ClusterManager type
type MockClusterManager struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, cluster
func (_m *MockClusterManager) Create(ctx context.Context, cluster *interfaces.ClusterCreate) (*interfaces.ClusterCreateResponse, error) {
	ret := _m.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *interfaces.ClusterCreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ClusterCreate) (*interfaces.ClusterCreateResponse, error)); ok {
		return rf(ctx, cluster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ClusterCreate) *interfaces.ClusterCreateResponse); ok {
		r0 = rf(ctx, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ClusterCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.ClusterCreate) error); ok {
		r1 = rf(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, clusterName
func (_m *MockClusterManager) Delete(ctx context.Context, clusterName string) error {
	ret := _m.Called(ctx, clusterName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clusterName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, clusterName
func (_m *MockClusterManager) Get(ctx context.Context, clusterName string) (*interfaces.Cluster, error) {
	ret := _m.Called(ctx, clusterName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *interfaces.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.Cluster, error)); ok {
		return rf(ctx, clusterName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.Cluster); ok {
		r0 = rf(ctx, clusterName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockClusterManager) List(ctx context.Context, opts *interfaces.ListClustersOptions) (*interfaces.ClusterList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *interfaces.ClusterList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ListClustersOptions) (*interfaces.ClusterList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ListClustersOptions) *interfaces.ClusterList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ClusterList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.ListClustersOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, clusterName, update
func (_m *MockClusterManager) Update(ctx context.Context, clusterName string, update *interfaces.ClusterUpdate) error {
	ret := _m.Called(ctx, clusterName, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *interfaces.ClusterUpdate) error); ok {
		r0 = rf(ctx, clusterName, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockClusterManager creates a new instance of MockClusterManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterManager {
	mock := &MockClusterManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
