// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/jontk/slurm-client/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// MockAssociationManager is an autogenerated mock type for the AssociationManager type
type MockAssociationManager struct {
	mock.Mock
}

// BulkDelete provides a mock function with given fields: ctx, opts
func (_m *MockAssociationManager) BulkDelete(ctx context.Context, opts *interfaces.BulkDeleteOptions) (*interfaces.BulkDeleteResponse, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 *interfaces.BulkDeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.BulkDeleteOptions) (*interfaces.BulkDeleteResponse, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.BulkDeleteOptions) *interfaces.BulkDeleteResponse); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.BulkDeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.BulkDeleteOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, associations
func (_m *MockAssociationManager) Create(ctx context.Context, associations []*interfaces.AssociationCreate) (*interfaces.AssociationCreateResponse, error) {
	ret := _m.Called(ctx, associations)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *interfaces.AssociationCreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*interfaces.AssociationCreate) (*interfaces.AssociationCreateResponse, error)); ok {
		return rf(ctx, associations)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*interfaces.AssociationCreate) *interfaces.AssociationCreateResponse); ok {
		r0 = rf(ctx, associations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.AssociationCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*interfaces.AssociationCreate) error); ok {
		r1 = rf(ctx, associations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, opts
func (_m *MockAssociationManager) Delete(ctx context.Context, opts *interfaces.DeleteAssociationOptions) error {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.DeleteAssociationOptions) error); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, opts
func (_m *MockAssociationManager) Get(ctx context.Context, opts *interfaces.GetAssociationOptions) (*interfaces.Association, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *interfaces.Association
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.GetAssociationOptions) (*interfaces.Association, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.GetAssociationOptions) *interfaces.Association); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Association)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.GetAssociationOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountAssociations provides a mock function with given fields: ctx, accountName
func (_m *MockAssociationManager) GetAccountAssociations(ctx context.Context, accountName string) ([]*interfaces.Association, error) {
	ret := _m.Called(ctx, accountName)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountAssociations")
	}

	var r0 []*interfaces.Association
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*interfaces.Association, error)); ok {
		return rf(ctx, accountName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*interfaces.Association); ok {
		r0 = rf(ctx, accountName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*interfaces.Association)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAssociations provides a mock function with given fields: ctx, userName
func (_m *MockAssociationManager) GetUserAssociations(ctx context.Context, userName string) ([]*interfaces.Association, error) {
	ret := _m.Called(ctx, userName)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAssociations")
	}

	var r0 []*interfaces.Association
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*interfaces.Association, error)); ok {
		return rf(ctx, userName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*interfaces.Association); ok {
		r0 = rf(ctx, userName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*interfaces.Association)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockAssociationManager) List(ctx context.Context, opts *interfaces.ListAssociationsOptions) (*interfaces.AssociationList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *interfaces.AssociationList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ListAssociationsOptions) (*interfaces.AssociationList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.ListAssociationsOptions) *interfaces.AssociationList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.AssociationList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *interfaces.ListAssociationsOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, associations
func (_m *MockAssociationManager) Update(ctx context.Context, associations []*interfaces.AssociationUpdate) error {
	ret := _m.Called(ctx, associations)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*interfaces.AssociationUpdate) error); ok {
		r0 = rf(ctx, associations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateAssociation provides a mock function with given fields: ctx, user, account, cluster
func (_m *MockAssociationManager) ValidateAssociation(ctx context.Context, user string, account string, cluster string) (bool, error) {
	ret := _m.Called(ctx, user, account, cluster)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAssociation")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, user, account, cluster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, user, account, cluster)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, user, account, cluster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAssociationManager creates a new instance of MockAssociationManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssociationManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssociationManager {
	mock := &MockAssociationManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
