// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/jontk/slurm-client"
	mock "github.com/stretchr/testify/mock"
)

// MockWCKeyManager is an autogenerated mock type for the WCKeyManager type
type MockWCKeyManager struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, wckey
func (_m *MockWCKeyManager) Create(ctx context.Context, wckey *slurm.WCKeyCreate) (*slurm.WCKeyCreateResponse, error) {
	ret := _m.Called(ctx, wckey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *slurm.WCKeyCreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.WCKeyCreate) (*slurm.WCKeyCreateResponse, error)); ok {
		return rf(ctx, wckey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.WCKeyCreate) *slurm.WCKeyCreateResponse); ok {
		r0 = rf(ctx, wckey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.WCKeyCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.WCKeyCreate) error); ok {
		r1 = rf(ctx, wckey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, wckeyID
func (_m *MockWCKeyManager) Delete(ctx context.Context, wckeyID string) error {
	ret := _m.Called(ctx, wckeyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, wckeyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, wckeyName, user, cluster
func (_m *MockWCKeyManager) Get(ctx context.Context, wckeyName string, user string, cluster string) (*slurm.WCKey, error) {
	ret := _m.Called(ctx, wckeyName, user, cluster)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *slurm.WCKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*slurm.WCKey, error)); ok {
		return rf(ctx, wckeyName, user, cluster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *slurm.WCKey); ok {
		r0 = rf(ctx, wckeyName, user, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.WCKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, wckeyName, user, cluster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockWCKeyManager) List(ctx context.Context, opts *slurm.WCKeyListOptions) (*slurm.WCKeyList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *slurm.WCKeyList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.WCKeyListOptions) (*slurm.WCKeyList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.WCKeyListOptions) *slurm.WCKeyList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.WCKeyList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.WCKeyListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, wckeyName, user, cluster, update
func (_m *MockWCKeyManager) Update(ctx context.Context, wckeyName string, user string, cluster string, update *slurm.WCKeyUpdate) error {
	ret := _m.Called(ctx, wckeyName, user, cluster, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *slurm.WCKeyUpdate) error); ok {
		r0 = rf(ctx, wckeyName, user, cluster, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWCKeyManager creates a new instance of MockWCKeyManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWCKeyManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWCKeyManager {
	mock := &MockWCKeyManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
