// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/jontk/slurm-client"
	mock "github.com/stretchr/testify/mock"
)

// MockReservationManager is an autogenerated mock type for the ReservationManager type
type MockReservationManager struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, reservation
func (_m *MockReservationManager) Create(ctx context.Context, reservation *slurm.ReservationCreate) (*slurm.ReservationCreateResponse, error) {
	ret := _m.Called(ctx, reservation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *slurm.ReservationCreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.ReservationCreate) (*slurm.ReservationCreateResponse, error)); ok {
		return rf(ctx, reservation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.ReservationCreate) *slurm.ReservationCreateResponse); ok {
		r0 = rf(ctx, reservation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.ReservationCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.ReservationCreate) error); ok {
		r1 = rf(ctx, reservation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, reservationName
func (_m *MockReservationManager) Delete(ctx context.Context, reservationName string) error {
	ret := _m.Called(ctx, reservationName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, reservationName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, reservationName
func (_m *MockReservationManager) Get(ctx context.Context, reservationName string) (*slurm.Reservation, error) {
	ret := _m.Called(ctx, reservationName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *slurm.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*slurm.Reservation, error)); ok {
		return rf(ctx, reservationName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *slurm.Reservation); ok {
		r0 = rf(ctx, reservationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reservationName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockReservationManager) List(ctx context.Context, opts *slurm.ListReservationsOptions) (*slurm.ReservationList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *slurm.ReservationList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.ListReservationsOptions) (*slurm.ReservationList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.ListReservationsOptions) *slurm.ReservationList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.ReservationList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.ListReservationsOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, reservationName, update
func (_m *MockReservationManager) Update(ctx context.Context, reservationName string, update *slurm.ReservationUpdate) error {
	ret := _m.Called(ctx, reservationName, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *slurm.ReservationUpdate) error); ok {
		r0 = rf(ctx, reservationName, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockReservationManager creates a new instance of MockReservationManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationManager {
	mock := &MockReservationManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
