// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/jontk/slurm-client"
	mock "github.com/stretchr/testify/mock"
)

// MockQoSManager is an autogenerated mock type for the QoSManager type
type MockQoSManager struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, qos
func (_m *MockQoSManager) Create(ctx context.Context, qos *slurm.QoSCreate) (*slurm.QoSCreateResponse, error) {
	ret := _m.Called(ctx, qos)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *slurm.QoSCreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.QoSCreate) (*slurm.QoSCreateResponse, error)); ok {
		return rf(ctx, qos)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.QoSCreate) *slurm.QoSCreateResponse); ok {
		r0 = rf(ctx, qos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.QoSCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.QoSCreate) error); ok {
		r1 = rf(ctx, qos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, qosName
func (_m *MockQoSManager) Delete(ctx context.Context, qosName string) error {
	ret := _m.Called(ctx, qosName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, qosName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, qosName
func (_m *MockQoSManager) Get(ctx context.Context, qosName string) (*slurm.QoS, error) {
	ret := _m.Called(ctx, qosName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *slurm.QoS
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*slurm.QoS, error)); ok {
		return rf(ctx, qosName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *slurm.QoS); ok {
		r0 = rf(ctx, qosName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.QoS)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, qosName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockQoSManager) List(ctx context.Context, opts *slurm.ListQoSOptions) (*slurm.QoSList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *slurm.QoSList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.ListQoSOptions) (*slurm.QoSList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.ListQoSOptions) *slurm.QoSList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.QoSList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.ListQoSOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, qosName, update
func (_m *MockQoSManager) Update(ctx context.Context, qosName string, update *slurm.QoSUpdate) error {
	ret := _m.Called(ctx, qosName, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *slurm.QoSUpdate) error); ok {
		r0 = rf(ctx, qosName, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockQoSManager creates a new instance of MockQoSManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQoSManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQoSManager {
	mock := &MockQoSManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
