// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/jontk/slurm-client"
	mock "github.com/stretchr/testify/mock"
)

// MockSlurmClientInterface is an autogenerated mock type for the SlurmClient type
type MockSlurmClientInterface struct {
	mock.Mock
}

// Accounts provides a mock function with no fields
func (_m *MockSlurmClientInterface) Accounts() slurm.AccountManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Accounts")
	}

	var r0 slurm.AccountManager
	if rf, ok := ret.Get(0).(func() slurm.AccountManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.AccountManager)
		}
	}

	return r0
}

// Associations provides a mock function with no fields
func (_m *MockSlurmClientInterface) Associations() slurm.AssociationManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Associations")
	}

	var r0 slurm.AssociationManager
	if rf, ok := ret.Get(0).(func() slurm.AssociationManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.AssociationManager)
		}
	}

	return r0
}

// Analytics provides a mock function with no fields
func (_m *MockSlurmClientInterface) Analytics() slurm.AnalyticsManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Analytics")
	}

	var r0 slurm.AnalyticsManager
	if rf, ok := ret.Get(0).(func() slurm.AnalyticsManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.AnalyticsManager)
		}
	}

	return r0
}

// Capabilities provides a mock function with no fields
func (_m *MockSlurmClientInterface) Capabilities() slurm.ClientCapabilities {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 slurm.ClientCapabilities
	if rf, ok := ret.Get(0).(func() slurm.ClientCapabilities); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(slurm.ClientCapabilities)
	}

	return r0
}

// Close provides a mock function with no fields
func (_m *MockSlurmClientInterface) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Clusters provides a mock function with no fields
func (_m *MockSlurmClientInterface) Clusters() slurm.ClusterManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clusters")
	}

	var r0 slurm.ClusterManager
	if rf, ok := ret.Get(0).(func() slurm.ClusterManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.ClusterManager)
		}
	}

	return r0
}

// CreateTRES provides a mock function with given fields: ctx, req
func (_m *MockSlurmClientInterface) CreateTRES(ctx context.Context, req *slurm.CreateTRESRequest) (*slurm.TRES, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTRES")
	}

	var r0 *slurm.TRES
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.CreateTRESRequest) (*slurm.TRES, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.CreateTRESRequest) *slurm.TRES); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.TRES)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.CreateTRESRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfig provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetConfig(ctx context.Context) (*slurm.Config, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *slurm.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*slurm.Config, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *slurm.Config); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDBDiagnostics provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetDBDiagnostics(ctx context.Context) (*slurm.Diagnostics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDBDiagnostics")
	}

	var r0 *slurm.Diagnostics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*slurm.Diagnostics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *slurm.Diagnostics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.Diagnostics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDiagnostics provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetDiagnostics(ctx context.Context) (*slurm.Diagnostics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDiagnostics")
	}

	var r0 *slurm.Diagnostics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*slurm.Diagnostics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *slurm.Diagnostics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.Diagnostics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstance provides a mock function with given fields: ctx, opts
func (_m *MockSlurmClientInterface) GetInstance(ctx context.Context, opts *slurm.GetInstanceOptions) (*slurm.Instance, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *slurm.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.GetInstanceOptions) (*slurm.Instance, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.GetInstanceOptions) *slurm.Instance); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.GetInstanceOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstances provides a mock function with given fields: ctx, opts
func (_m *MockSlurmClientInterface) GetInstances(ctx context.Context, opts *slurm.GetInstancesOptions) (*slurm.InstanceList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetInstances")
	}

	var r0 *slurm.InstanceList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.GetInstancesOptions) (*slurm.InstanceList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.GetInstancesOptions) *slurm.InstanceList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.InstanceList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.GetInstancesOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLicenses provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetLicenses(ctx context.Context) (*slurm.LicenseList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLicenses")
	}

	var r0 *slurm.LicenseList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*slurm.LicenseList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *slurm.LicenseList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.LicenseList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShares provides a mock function with given fields: ctx, opts
func (_m *MockSlurmClientInterface) GetShares(ctx context.Context, opts *slurm.GetSharesOptions) (*slurm.SharesList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetShares")
	}

	var r0 *slurm.SharesList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.GetSharesOptions) (*slurm.SharesList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slurm.GetSharesOptions) *slurm.SharesList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.SharesList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slurm.GetSharesOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTRES provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) GetTRES(ctx context.Context) (*slurm.TRESList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTRES")
	}

	var r0 *slurm.TRESList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*slurm.TRESList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *slurm.TRESList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.TRESList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Info provides a mock function with no fields
func (_m *MockSlurmClientInterface) Info() slurm.InfoManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 slurm.InfoManager
	if rf, ok := ret.Get(0).(func() slurm.InfoManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.InfoManager)
		}
	}

	return r0
}

// Jobs provides a mock function with no fields
func (_m *MockSlurmClientInterface) Jobs() slurm.JobManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Jobs")
	}

	var r0 slurm.JobManager
	if rf, ok := ret.Get(0).(func() slurm.JobManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.JobManager)
		}
	}

	return r0
}

// Nodes provides a mock function with no fields
func (_m *MockSlurmClientInterface) Nodes() slurm.NodeManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Nodes")
	}

	var r0 slurm.NodeManager
	if rf, ok := ret.Get(0).(func() slurm.NodeManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.NodeManager)
		}
	}

	return r0
}

// Partitions provides a mock function with no fields
func (_m *MockSlurmClientInterface) Partitions() slurm.PartitionManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Partitions")
	}

	var r0 slurm.PartitionManager
	if rf, ok := ret.Get(0).(func() slurm.PartitionManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.PartitionManager)
		}
	}

	return r0
}

// QoS provides a mock function with no fields
func (_m *MockSlurmClientInterface) QoS() slurm.QoSManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for QoS")
	}

	var r0 slurm.QoSManager
	if rf, ok := ret.Get(0).(func() slurm.QoSManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.QoSManager)
		}
	}

	return r0
}

// Reconfigure provides a mock function with given fields: ctx
func (_m *MockSlurmClientInterface) Reconfigure(ctx context.Context) (*slurm.ReconfigureResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reconfigure")
	}

	var r0 *slurm.ReconfigureResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*slurm.ReconfigureResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *slurm.ReconfigureResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slurm.ReconfigureResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reservations provides a mock function with no fields
func (_m *MockSlurmClientInterface) Reservations() slurm.ReservationManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reservations")
	}

	var r0 slurm.ReservationManager
	if rf, ok := ret.Get(0).(func() slurm.ReservationManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.ReservationManager)
		}
	}

	return r0
}

// Users provides a mock function with no fields
func (_m *MockSlurmClientInterface) Users() slurm.UserManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 slurm.UserManager
	if rf, ok := ret.Get(0).(func() slurm.UserManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.UserManager)
		}
	}

	return r0
}

// Version provides a mock function with no fields
func (_m *MockSlurmClientInterface) Version() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// WCKeys provides a mock function with no fields
func (_m *MockSlurmClientInterface) WCKeys() slurm.WCKeyManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WCKeys")
	}

	var r0 slurm.WCKeyManager
	if rf, ok := ret.Get(0).(func() slurm.WCKeyManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slurm.WCKeyManager)
		}
	}

	return r0
}

// NewMockSlurmClientInterface creates a new instance of MockSlurmClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlurmClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlurmClientInterface {
	mock := &MockSlurmClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
