package mocks

// Re-export the generated mocks with backward-compatible names
// The actual mock implementations are in the mock_*.go files generated by mockery

// MockSlurmClient is an alias for the generated MockSlurmClientInterface
type MockSlurmClient = MockSlurmClientInterface

// MockJobManager is defined in mock_job_manager.go (generated)
// MockNodeManager is defined in mock_nodemanager.go (generated)
// MockPartitionManager is defined in mock_partitionmanager.go (generated)
// MockInfoManager is defined in mock_infomanager.go (generated)
// MockAccountManager is defined in mock_accountmanager.go (generated)
// MockQoSManager is defined in mock_qosmanager.go (generated)
// MockReservationManager is defined in mock_reservationmanager.go (generated)
